name: Test project

on:
  push:

jobs:
  ci:
    name: Black, isort and tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: '3.7'
          architecture: 'x64'
      - run: pip install -r requirements-dev.txt
      - run: black --check src tests
      - run: isort --check-only --recursive
      - run: python -m pytest -v
